const DataTable = () => {
    return (
        <div className="content">
            <div className="table-responsive">
                <table className="table table-striped table-sm" style={{ textAlign: "center" }}>
                    <thead>
                        <tr style={{ backgroundColor: "black", color: "white" }}>
                            <th>Id Profissional</th>
                            <th>Profissional</th>
                            <th>Id Operador</th>
                            <th>Operador</th>
                            <th>Data</th>
                            <th>Nível Suporte</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>3</td>
                            <td>Felipe</td>
                            <td>11</td>
                            <td>Caique</td>
                            <td>31/03/2020</td>
                            <td>1</td>
                        </tr>
                        <tr>
                            <td>1</td>
                            <td>Geovani</td>
                            <td>3</td>
                            <td>Matheus</td>
                            <td>18/04/2020</td>
                            <td>1</td>
                        </tr>
                        <tr>
                            <td>2</td>
                            <td>Daniel</td>
                            <td>1</td>
                            <td>Maria</td>
                            <td>22/04/2020</td>
                            <td>1</td>
                        </tr>
                        <tr>
                            <td>2</td>
                            <td>Daniel</td>
                            <td>16</td>
                            <td>Aline B</td>
                            <td>01/04/2020</td>
                            <td>2</td>
                        </tr>
                        <tr>
                            <td>3</td>
                            <td>Felipe</td>
                            <td>7</td>
                            <td>Aline</td>
                            <td>02/02/2020</td>
                            <td>2</td>
                        </tr>
                        <tr>
                            <td>3</td>
                            <td>Felipe</td>
                            <td>6</td>
                            <td>Silvia</td>
                            <td>18/03/2020</td>
                            <td>2</td>
                        </tr>
                        <tr>
                            <td>3</td>
                            <td>Felipe</td>
                            <td>15</td>
                            <td>Lucas S</td>
                            <td>23/05/2020</td>
                            <td>2</td>
                        </tr>
                        <tr>
                            <td>3</td>
                            <td>Felipe</td>
                            <td>11</td>
                            <td>Caique</td>
                            <td>07/03/2020</td>
                            <td>1</td>
                        </tr>
                        <tr>
                            <td>1</td>
                            <td>Geovani</td>
                            <td>7</td>
                            <td>Aline</td>
                            <td>26/04/2020</td>
                            <td>1</td>
                        </tr>
                        <tr>
                            <td>3</td>
                            <td>Felipe</td>
                            <td>10</td>
                            <td>Sandra</td>
                            <td>17/05/2020</td>
                            <td>2</td>
                        </tr>
                        <tr>
                            <td>2</td>
                            <td>Daniel</td>
                            <td>10</td>
                            <td>Sandra</td>
                            <td>21/04/2020</td>
                            <td>2</td>
                        </tr>
                        <tr>
                            <td>2</td>
                            <td>Daniel</td>
                            <td>3</td>
                            <td>Matheus</td>
                            <td>22/04/2020</td>
                            <td>1</td>
                        </tr>
                        <tr>
                            <td>3</td>
                            <td>Felipe</td>
                            <td>4</td>
                            <td>Amanda</td>
                            <td>05/03/2020</td>
                            <td>2</td>
                        </tr>
                        <tr>
                            <td>2</td>
                            <td>Daniel</td>
                            <td>1</td>
                            <td>Maria</td>
                            <td>20/05/2020</td>
                            <td>2</td>
                        </tr>
                        <tr>
                            <td>3</td>
                            <td>Felipe</td>
                            <td>11</td>
                            <td>Caique</td>
                            <td>29/03/2020</td>
                            <td>2</td>
                        </tr>
                        <tr>
                            <td>1</td>
                            <td>Geovani</td>
                            <td>7</td>
                            <td>Aline</td>
                            <td>17/03/2020</td>
                            <td>2</td>
                        </tr>
                        <tr>
                            <td>1</td>
                            <td>Geovani</td>
                            <td>7</td>
                            <td>Aline</td>
                            <td>06/04/2020</td>
                            <td>2</td>
                        </tr>
                        <tr>
                            <td>3</td>
                            <td>Felipe</td>
                            <td>10</td>
                            <td>Sandra</td>
                            <td>09/03/2020</td>
                            <td>1</td>
                        </tr>
                        <tr>
                            <td>2</td>
                            <td>Daniel</td>
                            <td>2</td>
                            <td>Renato</td>
                            <td>09/03/2020</td>
                            <td>2</td>
                        </tr>
                        <tr>
                            <td>1</td>
                            <td>Geovani</td>
                            <td>13</td>
                            <td>Lucas</td>
                            <td>27/02/2020</td>
                            <td>2</td>
                        </tr>
                        <tr>
                            <td>1</td>
                            <td>Geovani</td>
                            <td>6</td>
                            <td>Silvia</td>
                            <td>18/02/2020</td>
                            <td>2</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    )
}

export default DataTable;